// utils/demoMode.ts — Mode démonstration RIUSC
// Ce fichier fournit les données fictives pour le mode démo

export function isDemoActive(): boolean {
  if (typeof window === 'undefined') return false
  return localStorage.getItem('demo_mode') === 'true'
}

export function getDemoGroupe(): 'Intérêt' | 'Approuvé' {
  if (typeof window === 'undefined') return 'Intérêt'
  return (localStorage.getItem('demo_groupe') || 'Intérêt') as 'Intérêt' | 'Approuvé'
}

export const DEMO_RESERVISTE = {
  benevole_id: 'DEMO-001',
  prenom: 'Marie-Ève',
  nom: 'Tremblay',
  email: 'marie-eve.tremblay@example.com',
  telephone: '4185551234',
  photo_url: '/demo-avatar.jpg',
  groupe: 'Approuvé', // sera overridé dynamiquement
  date_naissance: '1988-06-15',
  adresse: '123 rue des Érables',
  ville: 'Sherbrooke',
  region: 'Estrie',
  contact_urgence_nom: 'Jean Tremblay',
  contact_urgence_telephone: '4185559876',
  contact_urgence_lien: 'Conjoint',
  contact_urgence_courriel: 'jean.tremblay@example.com',
  allergies_alimentaires: 'Arachides',
  allergies_autres: '',
  conditions_medicales: '',
  consent_photo: true,
  consent_photos: true,
}

export const DEMO_USER = { id: 'demo_user', email: DEMO_RESERVISTE.email }

export const DEMO_MESSAGES = [
  // ── Canal : général ──
  {
    id: 'demo-msg-1',
    user_id: 'demo-user-2',
    benevole_id: 'DEMO-002',
    auteur_nom: 'Jean-François Lavoie',
    auteur_photo: null,
    contenu: 'Comment est-ce qu\'on est informé qu\'un déploiement est imminent et qu\'on doit fournir nos disponibilités ?',
    canal: 'general',
    created_at: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
  {
    id: 'demo-msg-2',
    user_id: 'demo-user-3',
    benevole_id: 'DEMO-003',
    auteur_nom: 'Sophie Bergeron',
    auteur_photo: null,
    contenu: 'Tu vas recevoir un texto et un courriel te demandant de te rendre sur le portail pour y inscrire tes plages de disponibilités. C\'est rapide et bien expliqué !',
    canal: 'general',
    created_at: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
  {
    id: 'demo-msg-3',
    user_id: 'demo-user-4',
    benevole_id: 'DEMO-004',
    auteur_nom: 'Martin Gagnon',
    auteur_photo: null,
    contenu: 'Super expérience lors du dernier déploiement à Gatineau. L\'équipe était vraiment soudée. 💪',
    canal: 'general',
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'demo-msg-4',
    user_id: 'demo-user-2',
    benevole_id: 'DEMO-002',
    auteur_nom: 'Jean-François Lavoie',
    auteur_photo: null,
    contenu: 'Ceux qui ont été notifiés pour une participation au prochain déploiement, n\'oubliez pas de mettre vos disponibilités à jour sur le portail !',
    canal: 'general',
    created_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'demo-msg-5',
    user_id: 'demo-user-5',
    benevole_id: 'DEMO-005',
    auteur_nom: 'Isabelle Roy',
    auteur_photo: null,
    contenu: 'Merci pour le rappel ! C\'est fait de mon côté. 👍',
    canal: 'general',
    created_at: new Date(Date.now() - 1800000).toISOString(),
  },
  // ── Canal : questions ──
  {
    id: 'demo-msg-q1',
    user_id: 'demo-user-5',
    benevole_id: 'DEMO-005',
    auteur_nom: 'Isabelle Roy',
    auteur_photo: null,
    contenu: 'Où est-ce qu\'on trouve l\'information sur le lieu et l\'heure du prochain camp de qualification ?',
    canal: 'questions',
    created_at: new Date(Date.now() - 3600000 * 24).toISOString(),
  },
  {
    id: 'demo-msg-q2',
    user_id: 'demo-user-3',
    benevole_id: 'DEMO-003',
    auteur_nom: 'Sophie Bergeron',
    auteur_photo: null,
    contenu: 'Tout est disponible dans le cahier du participant qui vous sera envoyé suite à votre inscription. Tu vas avoir toutes les infos là-dedans !',
    canal: 'questions',
    created_at: new Date(Date.now() - 3600000 * 23).toISOString(),
  },
  {
    id: 'demo-msg-q3',
    user_id: 'demo-user-6',
    benevole_id: 'DEMO-006',
    auteur_nom: 'Alexandre Côté',
    auteur_photo: null,
    contenu: 'Question pour ceux qui ont déjà fait un déploiement : combien de temps à l\'avance on est avisé généralement ?',
    canal: 'questions',
    created_at: new Date(Date.now() - 3600000 * 8).toISOString(),
  },
  {
    id: 'demo-msg-q4',
    user_id: 'demo-user-4',
    benevole_id: 'DEMO-004',
    auteur_nom: 'Martin Gagnon',
    auteur_photo: null,
    contenu: 'Dès qu\'on reçoit la demande, on est avisé de soumettre nos disponibilités. On a environ 8h pour les inscrire sur le portail. Ensuite, l\'équipe fait l\'analyse et choisit les personnes retenues pour la prochaine vague — tu seras informé par texto et courriel. Après cette confirmation, tu as généralement 24 à 48h pour te préparer.',
    canal: 'questions',
    created_at: new Date(Date.now() - 3600000 * 7).toISOString(),
  },
  {
    id: 'demo-msg-q5',
    user_id: 'demo-user-2',
    benevole_id: 'DEMO-002',
    auteur_nom: 'Jean-François Lavoie',
    auteur_photo: null,
    contenu: 'Comment ça fonctionne pour le certificat S\'initier ? Je l\'ai terminé en ligne mais je ne le vois pas encore sur mon portail.',
    canal: 'questions',
    created_at: new Date(Date.now() - 3600000 * 3).toISOString(),
  },
  {
    id: 'demo-msg-q6',
    user_id: 'demo-user-3',
    benevole_id: 'DEMO-003',
    auteur_nom: 'Sophie Bergeron',
    auteur_photo: null,
    contenu: 'Tu peux uploader ton certificat PDF directement dans la section Formation. Il sera ajouté automatiquement à ton dossier.',
    canal: 'questions',
    created_at: new Date(Date.now() - 3600000 * 2.5).toISOString(),
  },
  // ── Canal : entraide ──
  {
    id: 'demo-msg-e1',
    user_id: 'demo-user-4',
    benevole_id: 'DEMO-004',
    auteur_nom: 'Martin Gagnon',
    auteur_photo: null,
    contenu: 'Petit conseil pour ceux qui se préparent à un premier déploiement : amenez des vêtements en couches. Le matin c\'était froid mais l\'après-midi en plein soleil avec le travail physique, on avait chaud ! 🥵',
    canal: 'entraide',
    created_at: new Date(Date.now() - 3600000 * 48).toISOString(),
  },
  {
    id: 'demo-msg-e2',
    user_id: 'demo-user-5',
    benevole_id: 'DEMO-005',
    auteur_nom: 'Isabelle Roy',
    auteur_photo: null,
    contenu: 'Petit rappel : lorsque vous arrivez sur le site de déploiement, vous devez vous inscrire à l\'endroit désigné. Vous recevrez toutes les informations pertinentes ainsi que vos ÉPI de base à ce moment-là. 👍',
    canal: 'entraide',
    created_at: new Date(Date.now() - 3600000 * 47).toISOString(),
  },
  {
    id: 'demo-msg-e3',
    user_id: 'demo-user-6',
    benevole_id: 'DEMO-006',
    auteur_nom: 'Alexandre Côté',
    auteur_photo: null,
    contenu: 'Pour savoir quoi apporter en déploiement, allez voir la page Informations pratiques sur le portail. Tout y est détaillé ! 📋',
    canal: 'entraide',
    created_at: new Date(Date.now() - 3600000 * 12).toISOString(),
  },
  {
    id: 'demo-msg-e4',
    user_id: 'demo-user-3',
    benevole_id: 'DEMO-003',
    auteur_nom: 'Sophie Bergeron',
    auteur_photo: null,
    contenu: 'Après mon premier déploiement, j\'étais un peu chamboulée. Si ça arrive à quelqu\'un, c\'est normal. Le débriefing d\'équipe m\'a vraiment aidée. N\'hésitez pas à en parler. ❤️',
    canal: 'entraide',
    created_at: new Date(Date.now() - 3600000 * 6).toISOString(),
  },
  {
    id: 'demo-msg-e5',
    user_id: 'demo-user-2',
    benevole_id: 'DEMO-002',
    auteur_nom: 'Jean-François Lavoie',
    auteur_photo: null,
    contenu: 'Tellement vrai Sophie. On est une équipe, pas juste sur le terrain. 🤝',
    canal: 'entraide',
    created_at: new Date(Date.now() - 3600000 * 5.5).toISOString(),
  },
  // ── Canal : deploiement → vide (aucun message) ──
]

export const DEMO_FORMATIONS = [
  {
    id: 'demo-f1',
    nom: "S'initier à la sécurité civile",
    catalogue: "S'initier à la sécurité civile",
    session: "S'initier à la sécurité civile",
    role: 'Participant',
    resultat: 'Réussi',
    etat_validite: 'Valide',
    date_reussite: '2025-11-20',
    date_expiration: null,
    commentaire: '',
    has_fichier: true,
    fichiers: [{ name: 'Certificat_Sinitier.pdf', url: null }],
  },
  {
    id: 'demo-f2',
    nom: 'Le bénévole en sécurité civile (AQBRS)',
    catalogue: 'Le bénévole en sécurité civile (AQBRS)',
    session: 'Le bénévole en sécurité civile (AQBRS)',
    role: 'Participant',
    resultat: 'Réussi',
    etat_validite: 'Valide',
    date_reussite: '2025-12-05',
    date_expiration: null,
    commentaire: '',
    has_fichier: false,
    fichiers: [],
  },
  {
    id: 'demo-f3',
    nom: 'Cohorte 7 - Camp de qualification - TR',
    catalogue: 'Cohorte 7 - Camp de qualification - TR',
    session: 'Cohorte 7 - Camp de qualification - TR',
    role: 'Participant',
    resultat: 'Réussi',
    etat_validite: 'Valide',
    date_reussite: '2026-01-18',
    date_expiration: null,
    commentaire: '',
    has_fichier: true,
    fichiers: [{ name: 'Attestation_Camp_Cohorte7.pdf', url: null }],
  },
]

export const DEMO_DEPLOIEMENTS = [
  {
    id: 'demo-dep-1',
    deploiement_id: 'demo-dep-1',
    nom_deploiement: 'Inondations printanières - Gatineau',
    nom_sinistre: 'Inondations printanières 2026',
    nom_demande: 'Demande MSP-2026-045',
    organisme: 'Ville de Gatineau',
    date_debut: '2026-03-15',
    date_fin: null,
    lieu: 'Gatineau, secteur Hull',
    statut: 'actif',
    type_incident: 'Inondation',
  },
]

export const DEMO_DISPONIBILITES = [
  {
    id: 'demo-dispo-1',
    monday_item_id: 'demo-mi-1',
    benevole_id: 'DEMO-001',
    deploiement_id: 'demo-dep-1',
    nom_deploiement: 'Inondations printanières - Gatineau',
    nom_sinistre: 'Inondations printanières 2026',
    date_debut: '2026-03-16',
    date_fin: '2026-03-19',
    statut: 'Disponible',
    statut_version: 'Active',
    transport: 'autonome',
    commentaire: 'Disponible jour et nuit',
    envoye_le: '2026-03-10',
    repondu_le: '2026-03-10',
    user_id: 'demo_user',
  },
]
